SCALE = 2

HEIGHT = 450 * SCALE
WIDTH = 400 * SCALE

ACCELERATION = 0.5 * SCALE
FRICTION = -0.12
GRAVITY = 0.5 * SCALE

FLOOR_HEIGHT = 20 * SCALE
PLATFORM_HEIGHT = 12 * SCALE
PLATFORM_MIN_WIDTH = 50 * SCALE
PLATFORM_MAX_WIDTH = 100 * SCALE
PLATFORM_MIN_Y_GAP = 140 * SCALE
PLATFORM_MAX_Y_GAP = 160 * SCALE
MOVING_PLATFORM_BASE_SPEED = 1 * SCALE

PLAYER_SIZE = 40 * SCALE
GLIDER_SIZE = 60 * SCALE
JUMP_VELOCITY = -15 * SCALE
JUMP_CANCEL_VELOCITY = -3 * SCALE
GLIDER_VELOCITY = 1 * SCALE

WATSON_WIDTH = 160 * SCALE
WATSON_HEIGHT = 215 * SCALE

FONT_SIZE = 20 * SCALE

FPS = 60
